### ISSUE TITLE
Can you give me your document about this source? i want to research that. Thank you so much!

### ISSUE THREAD

**Issue by imax16041998** [andipro123/Blockchain-based-E-Voting#3]
this is my email: imax16041998@gmail.com
pls reply me soon

**Comment by andipro123** [comment]
Replied to you via email :)

**Comment by Aju2001** [comment]
what is the login id and password to have a look at the project?

**Comment by Titan1911** [comment]
Can you please mail that to me too?
email: sahilahuja1911@gmail.com
