### ISSUE TITLE
How can i get the key to vote? And Key Generator.ipynb is error 

### ISSUE THREAD

**Issue by imax16041998** [andipro123/Blockchain-based-E-Voting#5]
What should I fill out here? How do I get the key?
![image](https://user-images.githubusercontent.com/50973410/105370057-c00c8480-5c35-11eb-8df6-933af001ea32.png)
And this is error in Key Generator.ipynb? 
![image](https://user-images.githubusercontent.com/50973410/105370219-efbb8c80-5c35-11eb-9e78-f3357afa6327.png)

This is my email: imax16041998@gmail.com

**Comment by imax16041998** [comment]
And please tell me how to use this project. No paper say it?

**Comment by andipro123** [comment]
variable x is not required anywhere. Just copy-paste the 'n' value and 'd' from the notebook into the textbox.
