### ISSUE TITLE
ImportError: cannot import name 'merkleTree' from 'poll.merkleTree' (unknown location)

### ISSUE THREAD

**Issue by Isaac009** [andipro123/Blockchain-based-E-Voting#8]
Missing file.

**Comment by seetharamaiah** [comment]
hai sir. i am getting same exception when i was excuting this project. so please suggest me solution for that.

ImportError: cannot import name 'merkleTree' from 'poll.merkleTree'

**Comment by andipro123** [comment]
Please clone my repo "https://github.com/andipro123/merkle-tree-Python" into this poll/. That error will be solved.

**Comment by Vicky8689** [comment]
> Please clone my repo "https://github.com/andipro123/merkle-tree-Python" into this poll/. That error will be solved.

Sir thi erro is no solve I am clone yor repo
